### ISSUE TITLE
provide an option to exclude

### ISSUE THREAD

**Issue by derekschrock** [cristianyxen/jailaudit#1]
We can run jailaudit on all or a given list however in some cases it might be easier provide a list to exclude.  Run on all except a small number.

Would it be possible to have an option to run on all but exclude a given list?

**Comment by cristianyxen** [comment]
What about using _jailaudit list - ALL | grep -v ^jailname_ ?

**Comment by derekschrock** [comment]
That's possible but thought it might be easier/better to have it as an option of script.  If you think that piping to grep is best we can close this issue.

**Comment by cristianyxen** [comment]
I really would like to not add more complicated output filtering code to the script when doing it the unix way is working good enough.
